### ISSUE TITLE
[RFE] Design improvements of CPU view

### ISSUE THREAD

**Issue by genodeftest** [kamgurgul/cpu-info#10]
Thank you very much for providing this useful piece of software!

I would like to suggest a more structured design of the "CPU" view. Currently, it looks like this:

	ABI
	Cores
		Core 0 [clock rate]
		Core 1 [clock rate]
		Core 2 [clock rate]
		Core 3 [clock rate]
		…
	Features [of core 0]
	CPU implementer [of core 0]
	CPU architecture [of core 0]
	CPU variant [of core 0]
	CPU part [of core 0]
	CPU revision [of core 0]
	Features [of core 1]
	CPU implementer [of core 1]
	CPU architecture [of core 1]
	[…]

There are two minor issues with this layout:
1. It is quite verbose although it does not provide much information because most of the cores have the same properties
2. There is no visual distinction which properties belong to which CPU.

Some ideas on how to improve the user interface:
a) Display the CPU properties block in a collapsed block indented below the clock rate, like this:

	ABI
	Cores
		- Core 0 [clock rate]
			Features [of core 0]
			CPU implementer [of core 0]
			CPU architecture [of core 0]
			CPU variant [of core 0]
			CPU part [of core 0]
			CPU revision [of core 0]
		- Core 1 [clock rate]
			Features [of core 1]
			CPU implementer [of core 1]
			CPU architecture [of core 1]
			[…]
		+ Core 2 [clock rate]
		+ Core 3 [clock rate]
		…

  * Pro: easier to read, easy visual structure and attribution of properties to a core
  * Con: Needs expandable items

b) Display a CPU core type for cores with identical properties (except the clock rate) like this:

	ABI
	Cores
		Core 0 [clock rate]
			Core type: A
		Core 1 [clock rate]
			Core type: A
		Core 2 [clock rate]
			Core type: B
		Core 3 [clock rate]
			Core type: B
		…
	Core type A:
		Features [of core 0, 1]
		CPU implementer [of core 0, 1]
		CPU architecture [of core 0, 1]
		CPU variant [of core 0, 1]
		CPU part [of core 0, 1]
		CPU revision [of core 0, 1]
	Core type B:
		Features [of core 2, 3]
		CPU implementer [of core 2, 3]
		CPU architecture [of core 2, 3]
		[…]

I'm currently using version 4.1.0 from F-droid store on Android 8.1.0.

**Comment by isarrider** [comment]
I propose an enhancement of the enhancement...
As I still use this tiny thing to check for wakelocks
https://github.com/bvalosek/cpuspy
maybe its functions can be integrated in here...
Prob mostly the deep sleep (per core nowadays) is of interest...

**Comment by kamgurgul** [comment]
Changed in 4.4.0
