### ISSUE TITLE
Create Weblate/Crowdin account for translating

### ISSUE THREAD

**Issue by inson1** [kamgurgul/cpu-info#100]
It would be easier than creating PRs.

**Comment by kamgurgul** [comment]
It is already planned but won't be done soon

**Comment by inson1** [comment]
@kamgurgul Then why do you close that?

**Comment by inson1** [comment]
Oh Its duplicate #45

**Comment by inson1** [comment]
sorry for spam, I'm just reorganizing my solved issues - jg8tzJHCu0Qcc1zJGcht
