### ISSUE TITLE
camera number count wrong at v4.7

### ISSUE THREAD

**Issue by BackMountainDevil** [kamgurgul/cpu-info#102]
version: 4.7

device:  [Xiaomi 6](https://www.mi.com/mi6) 

os: [lineageos20 android 13](https://wiki.lineageos.org/devices/sagit/)

the real number of camera could be found at official site and the os web, is 3.

app Hardware -Camera. Amount 4.

![19860_1698238125_hd](https://github.com/kamgurgul/cpu-info/assets/59185302/ca441942-a222-4dbd-b8c1-192511da0913)

![19861_1698238222_hd](https://github.com/kamgurgul/cpu-info/assets/59185302/d0675a86-0de2-4e43-828b-6af3465e2ae5)

**Comment by kamgurgul** [comment]
Version 5.0.0 is based on Camera2 and will additionally display number of lenses

**Comment by BackMountainDevil** [comment]
so it is not a bug, right? I check release and no v5.0.0.

**Comment by kamgurgul** [comment]
Not a bug, amount of cameras doesn't match amount of lens - in version 5.0.0 lens number is also included
