### ISSUE TITLE
No SOC Temperature  on Exynos based devices

### ISSUE THREAD

**Issue by Asneb** [kamgurgul/cpu-info#108]
Device:SAMSUNG A54E
Android Version: 14
![Screenshot_20240123_105204_CPU Info.jpg](https://github.com/kamgurgul/cpu-info/assets/87947601/bff7e305-1aa3-4922-9ede-da93cc1444d6)

**Comment by kamgurgul** [comment]
Unfortunately if Samsung doesn't expose temps in sensors or in files then it wouldn't be possible to display it for non rooted devices. I don't have any Samsung device to search for Samsung specific sensors
