### ISSUE TITLE
Cannot Scroll on Fire TV 

### ISSUE THREAD

**Issue by realAllonZ** [kamgurgul/cpu-info#111]
Thanks for the wonderful app! It has been very useful on a lot of my devices.

With the latest release it now does not scroll with stock remote or air remote. Any possibility this issue will be fixed?

F-droid
CPU Info 5.2.0
Fire OS 7.6.6.4
Model AFTDCT31

**Comment by kamgurgul** [comment]
Probably it is caused by Compose migration :( Is there any available emulator of this this tv?

**Comment by kamgurgul** [comment]
Fixed in 5.3.0
