### ISSUE TITLE
The SoC name of the CPU shows "unknown"

### ISSUE THREAD

**Issue by Char11e** [kamgurgul/cpu-info#114]
When using the v5.3.0 program on the Nokia 8.3 5G model, the SoC name will be displayed as unknown, but the ABI can display arm64-v8a

Android ver: 12

**Comment by Char11e** [comment]
It should show Qualcomm Snapdragon 765G

**Comment by kamgurgul** [comment]
I need to mark this in the main Readme because it is a recurring problem. SoC neme is controlled by external lib: https://github.com/pytorch/cpuinfo If there is no support for particular CPU it won't be displayed
