### ISSUE TITLE
some things unknown on pixel 6 pro (raven) BUG!!!!

### ISSUE THREAD

**Issue by Raschi1234** [kamgurgul/cpu-info#169]
i was checking some things and i discovered that the SoC name is unknown also the serial number is unknown and the sound card is unknown, too.
I'll put some screenshot.
Please fix this, it's annoying.

![Screenshot_20240707-082433](https://github.com/kamgurgul/cpu-info/assets/141054595/bd058022-2c1a-4502-a689-ace803411937)
![Screenshot_20240707-082420](https://github.com/kamgurgul/cpu-info/assets/141054595/a4d5fc6c-a03e-46fc-a3d6-12bb789dcd94)
![Screenshot_20240707-082400](https://github.com/kamgurgul/cpu-info/assets/141054595/7953e756-94a3-4521-9d3a-11736db3b126)

**Comment by kamgurgul** [comment]
It is not possible to fix it on my end because SoC name is taken from external library
