### ISSUE TITLE
Add new features "Features" in the hardware section and additional information in the storage section of the INFO CPU application

### ISSUE THREAD

**Issue by ammarraisafti** [kamgurgul/cpu-info#22]
# Component
The following are the features I want to recommend:

- **FEATURES.**
_Add information about Bluetooth, Bluetooth LE, GPS, NFC, USB Accessories, Wifi and WifiDirect._

- Add **"USB OTG"** information in the "STORAGE" information in the "Hardware" section.

# Proposal description
Propose a new feature in the "Hardware" section of the CPU application developer Info to add the "FEATURES" feature in that section, and the developer must modify the section to put information about "Bluetooth, Bluetooth LE, GPS, NFC, USB Accessory, Wifi and WifiDirect so that users can find out full information of their android device, and developers should add information in the "Storage" section of information about "USB OTG".
![Screenshot_20180210-024513-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518207431/mklheofrqxhjbh4ge9bd.png)

# Mockups / Examples
A sample image is visible if the developer has added the feature in the "Hardware" section, which adds the "Features" feature and the "USB OTG" information in the "Storage" section.

![Screenshot_20180210-024629-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518207988/v5lrwfvnztvllmtx1sls.png)

![Screenshot_20180210-024629-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518208249/wg7vziskx4tzanuf8a4r.png)

![Screenshot_20180210-024223-picsay.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518208359/bfqslyx9asmbiiztacix.png)

# Benefits
With the presence of the feature "FEATURES" in the Hardware section of CPU Info application, users will get information about bluetooth and bluetooth LE, users also get GPS information, NFC and USB ACCESSORI on their device support or not and users will get information about Wifi, Wifi direct on their device, so users will be satisfied, getting the feature and knowing that their device is equipped with the feature, and no doubt about it. And once the developer adds "USB OTG" information in the Storage section, users will get information about "USB OTG" equipped and supported on their device. And that's a huge benefit in getting CPU Users app info, so users do not have to worry and worry about their devices anymore, because CPU apps have provided very good and useful information to them.

**Comment by kamgurgul** [comment]
All features are added in version 4.4.0 (not released yes) in "Hardware" section.
![device-2019-12-21-201350](https://user-images.githubusercontent.com/6876371/71312739-c4f97600-242e-11ea-8421-d7a8a0ade548.png)
