### ISSUE TITLE
CPU monitor

### ISSUE THREAD

**Issue by Kukulkan2019** [kamgurgul/cpu-info#23]
This app needs to have a status bar icon so that the user can look at the top of his/her device and see the CPU and battery temp., etc., in real time. Other similar apps offered elsewhere already have this all important feature.

**Comment by RichyHBM** [comment]
An alternative to this could be to have the information as a quick tile. I'll see if I can get a PR in soon

**Comment by Kukulkan2019** [comment]
Right, there are alternatives to everything. I and others would need something for CPU/GPU and all important battery temp in real time like for intense gaming activity that was small enough not to interfere with the dispay particularly for tablets in landscape mode.

**Comment by RichyHBM** [comment]
Why has it been closed?

**Comment by Kukulkan2019** [comment]
I'm sorry, quite frankly I closed it accidentally I'll open it again as
soon as I get a chance you see I'm running out of prepaid load...


Brennan

**Comment by Kukulkan2019** [comment]
Thank you...
