### ISSUE TITLE
Question: How Is CPU Load Calculated?

### ISSUE THREAD

**Issue by vicenters1** [kamgurgul/cpu-info#256]
I'm currently exploring methods to retrieve CPU load on Android devices. I'd like to understand the approach your app uses for calculating CPU load on Android.

- Are you leveraging [OSHI](https://github.com/oshi/oshi) for this calculation? If not (because I believe that will be the answer after my quick search on the source code), could you share insights into the thought process behind opting for a different solution?
- Are there specific Android-compatible techniques or APIs you recommend for retrieving CPU load data in a non-rooted environment?

Thank you!

**Comment by kamgurgul** [comment]
You can find full implementation here: https://github.com/kamgurgul/cpu-info/blob/master/shared/src/androidMain/kotlin/com/kgurgul/cpuinfo/data/provider/CpuDataProvider.android.kt

You can take current frequency from file.
