### ISSUE TITLE
want to create a logo representing your project in the future

### ISSUE THREAD

**Issue by damahsyari** [kamgurgul/cpu-info#3]
Hello @kamgurgul , Im Damah
I'm a graphic designer and i want your permission to design a logo and an icon for your application.
Best regards.

**Comment by kamgurgul** [comment]
PR with new ideas are always welcome :) Please keep in mind all Android requirements for icons. I'm closing this issue now.

**Comment by damahsyari** [comment]
of course sir .. i will offer original ideas original. do you allow me to create logo design for your application? you do not need to use it if you do not like it
