### ISSUE TITLE
Please explain why it shows two drives.

### ISSUE THREAD

**Issue by bat999** [kamgurgul/cpu-info#34]
Hi
My phone is Xiaomi-redmi-go.
It only has the one 16GB internal drive but CPU Info shows it twice as Internal and External.
Here is a screenshot...
![img_eggsif_1371611960617102879](https://user-images.githubusercontent.com/640761/68324094-9f065500-00be-11ea-8e90-973597385010.jpg)

**Comment by kamgurgul** [comment]
It is releated to the Android storage separation policy. You can find more here: https://stackoverflow.com/questions/5092591/what-are-the-differences-among-internal-storage-external-storage-sd-card-and-r
