### ISSUE TITLE
Current version not available in F-Droid Store

### ISSUE THREAD

**Issue by Krawei** [kamgurgul/cpu-info#41]
Dear team,

when I take a look on google play store the current version is 4.4.2 in the F-Droid store the current version is 4.3.3.

What's the reason for this gap? Is there a bug in the build process?

Please fix this.

Kind Regards,

Krawei

**Comment by licaon-kter** [comment]
> What's the reason for this gap? Is there a bug in the build process?
Yes and no, we can't use Autoupdate as versionCode is not static.

Also these libs need to either be build during app building or taken from a trusted (by F-Droid) maven repo:
https://github.com/kamgurgul/cpu-info/tree/master/app/libs
https://github.com/kamgurgul/cpu-info/tree/master/external/cpuinfo

**Comment by Bubu** [comment]
Fixed it: https://gitlab.com/fdroid/fdroiddata/-/commit/2a5529351964e644eb096fe0901238c3c4d7445b

But yes, replacing the opencsv jar file with a maven dependency would help already. (building the libcpuinfo from source during the fdroid build is easy enough now I figured that out once.)

**Comment by kamgurgul** [comment]
Thanks a lot for it :) However, I would suggest to use version 4.4.3 if it isn't merged yet to the F-Droid main lane.

**Comment by Bubu** [comment]
I'll add 4.4.3 as well, sure!

**Comment by sm4rk0** [comment]
Thanks, 4.4.2 is released to f-droid!
