### ISSUE TITLE
Root Check

### ISSUE THREAD

**Issue by free-tinker** [kamgurgul/cpu-info#48]
Hello,
my phone has lineage os in it and i've done removing the SU.
but the cpu-info still informing that my phone is rooted.
so, what is wrong with that ?
or cpu-info parameter for root check is not the existence of SU ?

Thank You

**Comment by kamgurgul** [comment]
In general there's no reliable way to determine whether device is rooted or not. CPU info is based on methods described here: https://stackoverflow.com/a/8097801
