### ISSUE TITLE
android studio 3.1.2 read time out

### ISSUE THREAD

**Issue by renhuihhh** [kamgurgul/cpu-info#5]
hi my friend,
     I think it's my IDE error, I have cloned your repository 3 months ago and it was successfully built, but I can't today. When I sync the project in android studio  the " read time out" error occurs. However, even if I pull the latest codes it 's still the same problem.
     May be it's android studio's bug, could you give me a help

`下午2:29	Outdated Kotlin Runtime
				Your version of Kotlin runtime in 'Gradle: org.jetbrains.kotlin:kotlin-stdlib:1.2.10@jar' library is 1.2.10-release-109 (1.2.10), while plugin version is 1.2.30-release-Studio3.1-1.
				Runtime library should be updated to avoid compatibility problems.
				Update Runtime Ignore

下午2:31	Gradle sync failed: Read timed out
				Consult IDE log for more details (Help | Show Log) (2m 0s 704ms)

下午2:33	Gradle sync started

下午2:33	Gradle sync failed: Read timed out
				Consult IDE log for more details (Help | Show Log) (32s 52ms)`

**Comment by kamgurgul** [comment]
Please send me whole Gradle sync log. Maybe it is temporary problem with maven/jcenter repository.

**Comment by renhuihhh** [comment]
Thank you , and I found this is caused by kotlin plugin version.
