### ISSUE TITLE
[Request]Need Google Service Framwork Info

### ISSUE THREAD

**Issue by HemanthJabalpuri** [kamgurgul/cpu-info#51]
@kamgurgul
Uncertified devices need a GoogleServiceFramwork ID which is used to register device in https://www.google.com/android/uncertified/

We can get that ID using some apps like Get ID at https://f-droid.org/en/packages/makeinfo.com.getid/ and Device info at https://f-droid.org/en/packages/com.oF2pks.kalturadeviceinfos/

Can you please add that info your great app.

Thanks

**Comment by kamgurgul** [comment]
Will be added in `4.5.0`
