### ISSUE TITLE
support: where can i see AES hardware support

### ISSUE THREAD

**Issue by gcb** [kamgurgul/cpu-info#54]
Is AES hardware support show somewhere? (not sure i'm not seeing because the application doesn't show or my devices are missing it)

if not supported, can you please point me to new contributor docs?

Thank you!

**Comment by kamgurgul** [comment]
What do you mean by AES hardware support? Are you refering to AndroidKeystore AES support or sth different?

**Comment by gcb** [comment]
Maybe... android java is not my strong point.

I develop on C (not NDK either) for those devices. And use this app to look for specific test devices.

in this case i features like this in mind https://www.qualcomm.com/news/onq/2014/11/07/cryptographic-module-snapdragon-805-fips-140-2-certified

reading on https://developer.android.com/training/articles/keystore it seems what you mention is a combination of what i am looking for /plus/ android 9+.

**Comment by kamgurgul** [comment]
Info about StrongBox will be added in `4.6.0`
