### ISSUE TITLE
Copycat on Google Play

### ISSUE THREAD

**Issue by Poussinou** [kamgurgul/cpu-info#67]
Hi @kamgurgul 

I found https://play.google.com/store/apps/details?id=smartsolutions.traffic.dot.info.cpuinfo on the Google Play Store from [this developer](https://play.google.com/store/apps/developer?id=SmartSolutions~Tech). This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove this copy from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under Apache V2 license and this guy is violating it;
* He is falsely claiming he made the app;
* Provide some screenshots of your own app.

**Comment by kamgurgul** [comment]
Thank you for the info! I opened the request and we will see if Google will do something about it :)

**Comment by kamgurgul** [comment]
And it is gone :)
