### ISSUE TITLE
Sorry to create an unconcerned issue

### ISSUE THREAD

**Issue by masteraux1** [kamgurgul/cpu-info#7]
[PagedListAdapter with multiple ViewHolders scroll bug #375](https://github.com/googlesamples/android-architecture-components/issues/375)
I encounter a very annoying problem that i cannot add header in PagedListAdapter. So I go to google and find your issue. It seems in this issue this you have add header viewholder in PagedListAdapter perfectly.
Could you show me how you do it? This problem bother me for days. thank you!

**Comment by kamgurgul** [comment]
To use headers you need to have your own implementation of PagedListAdapter with custom differ. Probably you will need only submitList method. Rest of the solution is described in mentioned issue. 

Please keep all discussions related to the architecture components on their repositories.
