### ISSUE TITLE
SoC name not fond on Lenovo Xiaoxin Pad Pro

### ISSUE THREAD

**Issue by kolyneh** [kamgurgul/cpu-info#70]
SoC name not fond on Lenovo Xiaoxin Pad Pro, it should be Snapdragon 730G.

<img width="1062" alt="截屏2022-06-08 12 00 22" src="https://user-images.githubusercontent.com/13062910/172528759-1602e4d0-b1cc-4d86-8a53-5a405140a616.png">

**Comment by kamgurgul** [comment]
SoC name is discovered by this library: https://github.com/pytorch/cpuinfo 

If it is not yet supported it needs to be added there.
