### ISSUE TITLE
Feature Request: Instruction Width + ABI of the OS

### ISSUE THREAD

**Issue by cachius** [kamgurgul/cpu-info#72]
Hello, I'd like to suggest to add Instruction width 32/64bit and ABI version
 - mips
 - mips64
 - X86
 - X86–64
 - arm64-v8a
 - armeabi
 - armeabi-v7a
 of the OS to the Android tab. Often  APK sources offer a multitude of apks to choose from. For example [Bromite Webview](https://www.apkmirror.com/apk/bromite/bromite-system-webview/bromite-system-webview-103-0-5060-140-release/).
This info would help to choose the right one.
Also sometimes the ABI is an older 32bit one running on a 64bit capable CPU which is also good to know (think of Raspberry Pis).

**Comment by kamgurgul** [comment]
Info about ABI is already available: 
![Screenshot_20220908_200243](https://user-images.githubusercontent.com/6876371/189193849-fcb4d9af-2d99-4da7-87ab-205668674c9a.png)
