### ISSUE TITLE
Broken hardware

### ISSUE THREAD

**Issue by leohoppergit** [kamgurgul/cpu-info#73]
Hi there,
Would the app show broken hardware, as e.g. a nonfunctional Bluetooth module, which is physically available though. And if so, would the app tell me the altered status or can it just tell that the hardware is or is not available. Does it tell anything about functionality?

Thanks and regards!

**Comment by kamgurgul** [comment]
In general no. If system reports that specific hardware is available then app will show it. I'm not even sure how verification of nonfunctional modules could be detected.
