### ISSUE TITLE
update fdroid build (add autoupdate if possible)

### ISSUE THREAD

**Issue by phanirithvij** [kamgurgul/cpu-info#77]
Can the fdroid build be updated? It seems auto update is disabled for [this package](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.kgurgul.cpuinfo.yml#L117)
> MaintainerNotes: We can't use auto update because version code and name are dynamic.

Is it possible to get autoupdate to get working?

**Comment by kamgurgul** [comment]
Update added to the FDroid repo: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12762

I cannot use automatic app update because this dynamic versioning.
