### ISSUE TITLE
crash when switching to hardware tab

### ISSUE THREAD

**Issue by bjlockie** [kamgurgul/cpu-info#91]
It crashes every time I switch to the hardware tab.
Is there a log somewhere?
I can't find the version info but I just installed it on my new-to-me phone (Samsung Galaxy S20 FE).
I suspect it crashes trying to read the fingerprint sensor because that sensor has a problem.

**Comment by kamgurgul** [comment]
You are using outdated version - see #85 #83 #79

**Comment by bjlockie** [comment]
How do I see what version I have?
