### ISSUE TITLE
my new phone displays "unknown soc"

### ISSUE THREAD

**Issue by bjlockie** [kamgurgul/cpu-info#95]
My new phone displays "unknown soc".
It is also missing the CPU temperature but it has the battery temperature.
It is a Samsung Exynos 1330 (https://semiconductor.samsung.com/processor/mobile-processor/exynos-1330/) soc.
Galaxy A14 5G phone (the one with the Exynos (not the Mediatek Dimensity 700).
Android 13.

v 4.7.0 from the Google Play Store.

**Comment by kamgurgul** [comment]
Socket names are mapped by external lib https://github.com/pytorch/cpuinfo
Until it is not supported there it will be called `Unknown`
