### ISSUE TITLE
F-droid suggested version crashes

### ISSUE THREAD

**Issue by hackerb9** [kamgurgul/cpu-info#96]
Version 4.7 is available in F-Droid, but version 4.6 is still the default. As you know (#87) 4.6 is buggy and should not be recommended.

Please change the "suggested" version to always use the latest. Thanks!

![Screenshot_20230920-141045](https://github.com/kamgurgul/cpu-info/assets/10174223/4d3794cd-9479-43b2-b73f-430b16ebf7c3)

**Comment by BackMountainDevil** [comment]
how it crash?

**Comment by BackMountainDevil** [comment]
so solution should be change the suggested version.

**Comment by kamgurgul** [comment]
WIll be changed with https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13929
